# Generated by Django 5.2.5 on 2025-08-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('building', models.CharField(max_length=120)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['building', 'room_number'], name='classrooms__buildin_2445d5_idx'), models.Index(fields=['is_published'], name='classrooms__is_publ_d26589_idx')],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField()),
                ('preview_url', models.URLField(blank=True)),
                ('yaw', models.FloatField(default=0)),
                ('pitch', models.FloatField(default=0)),
                ('hfov', models.FloatField(default=90)),
                ('order', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
