# Generated by Django 5.2.5 on 2025-08-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('campus', models.CharField(choices=[('MAIN', 'Main Campus'), ('HSC', 'Health Sciences Center'), ('AMBLER', 'Ambler Campus'), ('CENTER_CITY', 'Center City'), ('JAPAN', 'Temple Japan')], default='MAIN', max_length=32)),
                ('preview', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_amplification', models.BooleanField(default=False)),
                ('class_capture', models.BooleanField(default=False)),
                ('web_conference', models.BooleanField(default=False)),
                ('handheld_microphone', models.BooleanField(default=False)),
                ('document_camera', models.BooleanField(default=False)),
                ('ceiling_microphone', models.BooleanField(default=False)),
                ('ceiling_camera', models.BooleanField(default=False)),
                ('web_conference_camera', models.BooleanField(default=False)),
                ('apple_tv', models.BooleanField(default=False)),
                ('instructor_pc_equipped', models.BooleanField(default=False)),
                ('assistive_listening_device', models.BooleanField(default=False)),
                ('whiteboards_count', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='classrooms.building')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField()),
                ('preview_url', models.URLField(blank=True)),
                ('yaw', models.FloatField(default=0)),
                ('pitch', models.FloatField(default=0)),
                ('hfov', models.FloatField(default=90)),
                ('order', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['building', 'room_number'], name='classrooms__buildin_692e59_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_published'], name='classrooms__is_publ_d26589_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='uniq_building_room_fk'),
        ),
    ]
