# Generated by Django 5.2.5 on 2025-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='preview',
            field=models.CharField(blank=True, help_text='e.g. /media/preview.jpeg', max_length=500),
        ),
        migrations.AlterField(
            model_name='classroomphoto',
            name='image_url',
            field=models.CharField(blank=True, help_text='e.g. /media/some.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='image_url',
            field=models.CharField(blank=True, help_text='e.g. /media/preview.jpeg', max_length=500),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='preview_url',
            field=models.CharField(blank=True, help_text='e.g. /media/preview.jpeg', max_length=500),
        ),
    ]
