# Generated by Django 5.2.5 on 2025-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
