# Generated by Django 5.2.5 on 2025-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_building_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='preview_image',
            field=models.CharField(blank=True, help_text='Shown on cards. e.g. /media/alter-101-preview.jpg', max_length=500),
        ),
    ]
