# Generated by Django 5.2.5 on 2025-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_classroom_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='more_info_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='classroom',
            name='book_url',
            field=models.CharField(blank=True, help_text='Booking URL from 25live', max_length=500),
        ),
    ]
