# Generated by Django 5.2.5 on 2025-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_building_more_info_url_building_tech_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='chalk_board',
            field=models.PositiveIntegerField(default=0, verbose_name='Chalkboards'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='env_light',
            field=models.BooleanField(default=False, verbose_name='Environmental Controls (Lighting)'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='projectors',
            field=models.PositiveIntegerField(default=0, verbose_name='Projectors'),
        ),
        migrations.AlterField(
            model_name='building',
            name='tech_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='tech_contact_email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='building',
            name='tech_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='apple_tv',
            field=models.BooleanField(default=False, verbose_name='Apple TV'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='assistive_listening_device',
            field=models.BooleanField(default=False, verbose_name='Assistive Listening Device'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='book_url',
            field=models.CharField(blank=True, help_text='Booking URL from 25Live', max_length=500, verbose_name='Booking URL'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='ceiling_camera',
            field=models.BooleanField(default=False, verbose_name='Ceiling Camera (Zoom)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='ceiling_microphone',
            field=models.BooleanField(default=False, verbose_name='Ceiling Microphone'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_capture',
            field=models.BooleanField(default=False, verbose_name='Class Capture (Panopto)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='document_camera',
            field=models.BooleanField(default=False, verbose_name='Document Camera'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='handheld_microphone',
            field=models.BooleanField(default=False, verbose_name='Handheld Microphone'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='instructor_pc_equipped',
            field=models.BooleanField(default=False, verbose_name='Instructor PC Equipped'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='voice_amplification',
            field=models.BooleanField(default=False, verbose_name='Voice Amplification (Speakers)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='web_conference',
            field=models.BooleanField(default=False, verbose_name='Web Conference'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='web_conference_camera',
            field=models.BooleanField(default=False, verbose_name='Web Conference Camera (PC)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='whiteboards_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Whiteboards'),
        ),
    ]
