# Generated by Django 5.2.5 on 2025-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_classroom_chalk_board_classroom_env_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='hdesk',
            field=models.BooleanField(default=False, verbose_name='Height adjustable desk/podium'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='instructor_monitor',
            field=models.BooleanField(default=False, verbose_name='Instructor Monitor'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='lavalier_microphone',
            field=models.BooleanField(default=False, verbose_name='Wireless Lavalier Micrphone (clipon)'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='podium_microhpone',
            field=models.BooleanField(default=False, verbose_name='Podium Microphone'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='ceiling_camera',
            field=models.BooleanField(default=False, verbose_name='Wall Mounted Camera (Zoom)'),
        ),
    ]
