# Generated by Django 5.2.5 on 2025-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_classroom_hdesk_classroom_instructor_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='interactive_display',
            field=models.BooleanField(default=False, verbose_name='Interactive Display'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lavalier_microphone',
            field=models.BooleanField(default=False, verbose_name='Wireless Lavalier Micrphone (Clipon)'),
        ),
    ]
