# Generated by Django 5.2.5 on 2025-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_classroom_interactive_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessPresentationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='wireless_presentations',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='classrooms.wirelesspresentationoption'),
        ),
    ]
