# Generated by Django 5.2.5 on 2025-09-16 15:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_remove_classroom_wireless_presentations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='apple_tv',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='web_conference',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='wireless_presentation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kramer', 'Kramer'), ('apple_tv', 'Apple TV'), ('screenbeam', 'ScreenBeam')], max_length=26, verbose_name='Wireless Presentation'),
        ),
    ]
