# Generated by Django 5.2.5 on 2025-10-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_remove_classroom_apple_tv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('youtube', 'YouTube Video'), ('link', 'External Link')], default='link', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('url', models.CharField(max_length=600)),
                ('thumbnail_url', models.CharField(blank=True, max_length=600)),
                ('summary', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classrooms.building')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['building', 'published'], name='classrooms__buildin_c230bc_idx'), models.Index(fields=['order', 'created_at'], name='classrooms__order_6deeae_idx')],
            },
        ),
    ]
