# Generated by Django 5.2.5 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_buildingresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='classroomphoto',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='panorama',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='panorama',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='building',
            name='preview_file',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='preview_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='classrooms/previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='classroomphoto',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='panoramas/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='preview_file',
            field=models.ImageField(blank=True, null=True, upload_to='panoramas/previews/%Y/%m/%d/'),
        ),
    ]
