# Generated by Django 5.2.5 on 2025-12-01 02:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_remove_building_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='seating_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tables and chairs', 'Tables and Chairs'), ('tablet armchairs', 'Tablet armchairs')], max_length=34, verbose_name='Seating Type'),
        ),
    ]
