# Generated by Django 5.2.5 on 2025-12-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0013_classroom_seating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Room type'),
        ),
    ]
