# Generated by Django 5.2.5 on 2025-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0014_classroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='stage',
            field=models.BooleanField(default=False, verbose_name='Stage'),
        ),
    ]
