# Generated by Django 5.2.5 on 2025-12-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0015_classroom_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='multilevel_podium',
            field=models.BooleanField(default=False, verbose_name='Level 2 podium or Level 3 podium'),
        ),
    ]
