# Generated by Django 5.2.5 on 2025-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0016_classroom_multilevel_podium'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='privacy_panel',
            field=models.BooleanField(default=False, verbose_name='Privacy panel for teacher desk'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
