# Generated by Django 5.2.5 on 2025-12-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0017_classroom_privacy_panel_alter_classroom_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='windows',
            field=models.BooleanField(default=False, verbose_name='Windows in classroom'),
        ),
    ]
