# Generated by Django 5.2.5 on 2025-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0018_classroom_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='door_windows',
            field=models.BooleanField(default=False, verbose_name='Door with window'),
        ),
    ]
