# Generated by Django 5.2.5 on 2025-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0019_classroom_door_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lock',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lock Type'),
        ),
    ]
