# Generated by Django 5.2.5 on 2025-12-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0020_classroom_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='projector_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Projector Model'),
        ),
    ]
