# Generated by Django 5.2.5 on 2025-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0021_classroom_projector_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='display_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Model and size'),
        ),
    ]
