# Generated by Django 5.2.5 on 2025-12-01 03:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0022_classroom_display_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='instructor_pc_equipped',
        ),
        migrations.AddField(
            model_name='classroom',
            name='pc_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('windows', 'windows PC'), ('MacOs', 'MacOs (Apple Mac)')], max_length=13, verbose_name='Operating System'),
        ),
    ]
