# Generated by Django 5.2.5 on 2025-12-01 04:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0023_remove_classroom_instructor_pc_equipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='touchscreen_presentation',
            field=models.BooleanField(default=False, verbose_name='Smart Touchscreen Presentation'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='pc_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('windows', 'Windows PC'), ('MacOs', 'MacOs (Apple Mac)')], max_length=13, verbose_name='Operating System'),
        ),
    ]
