# Generated by Django 5.2.5 on 2025-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0024_classroom_touchscreen_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lecd',
            field=models.BooleanField(default=False, verbose_name='LED/LCD Display'),
        ),
    ]
